

services:
  frontend:
    container_name: frontend
    image: frontendimage
    restart: always
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    restart: always
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  proxy:
    container_name: proxy
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt
       - ./ssl/localhost.key:/etc/ssl/private/localhost.key

volumes:
  mongodb-data:
